version: '0.1'

services:
  metadata-collector:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    image: data-catalog-metadata-collector:$DATA_CATALOG_SOLUTION_IMG_VERSION
    container_name: metadata-collector
    ports:
      - "2222:22"
    stdin_open: true
    tty: true
    volumes:
      - $DATA_CATALOG_SOLUTION_DATA/conf:/metadata_collector/conf
      - $DATA_CATALOG_SOLUTION_DATA/metadata_collector/logs:/metadata_collector/logs
      - $DATA_CATALOG_SOLUTION_DATA/ingestion/script:/metadata_collector/ingestion/script
    environment:
      - METADATA_COLLECTOR_CONFIG_FILE=/metadata_collector/conf/config_docker.ini
    networks:
      - data-catalog-network
#    command: ["tail", "-f", "/dev/null"]
    command: /bin/bash -c "/usr/sbin/sshd -D & tail -f /dev/null"

networks:
  data-catalog-network:
    external: true