version: '0.1'

services:
  metadata-collector:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    image: data-catalog-metadata-collector:0.1
    container_name: metadata-collector
    ports:
      - "8587:8587"
    volumes:
      - /DATA_CATALOG/data/metadata-collector/conf:/metadata-collector/conf
      - /DATA_CATALOG/data/metadata-collector/logs:/metadata-collector/logs
    environment:
      - METADATA_COLLECTOR_CONFIG_FILE=/metadata-collector/conf/config.yaml
#    command: ["tail", "-f", "/dev/null"]

